import type { CSSProperties } from 'react'

export const brandColors = {
  ink:      '#151515',
  notebook: '#f4e9cf',
  paper:    '#fffaf0',
  yolk:     '#f8d96a',
  teal:     '#17a6a3',
  tomato:   '#e6533f',
}

export const colors = {
  ink:       '#151515',
  cream:     '#fafaf8',
  white:     '#ffffff',
  notebook:  '#f4e9cf',
  paper:     '#fffaf0',
  yellow:    '#ffd426',
  yolk:      '#f8d96a',
  tomato:    '#e6533f',
  teal:      '#17a6a3',
  cobalt:    '#2858ff',
  mint:      '#36d59b',
  green:     '#d9ff69',
  red:       '#ff6b62',
  blue:      '#7bd8ef',
  purple:    '#b995ff',
  muted:     '#786e60',
  line:      '#20201d',
  greenDark: '#1e6f38',
  blueDark:  '#0d5c75',
  redDark:   '#9c231d',
  purpleDark:'#5735a7',
}

export const landingColorVars = {
  '--lr-ink': colors.ink,
  '--lr-cream': colors.cream,
  '--lr-white': colors.white,
  '--lr-notebook': colors.notebook,
  '--lr-paper': colors.paper,
  '--lr-yellow': colors.yellow,
  '--lr-yolk': colors.yolk,
  '--lr-tomato': colors.tomato,
  '--lr-teal': colors.teal,
  '--lr-cobalt': colors.cobalt,
  '--lr-mint': colors.mint,
  '--lr-green': colors.green,
  '--lr-red': colors.red,
  '--lr-blue': colors.blue,
  '--lr-purple': colors.purple,
  '--lr-muted': colors.muted,
  '--lr-line': colors.line,
  '--lr-green-dark': colors.greenDark,
  '--lr-blue-dark': colors.blueDark,
  '--lr-red-dark': colors.redDark,
  '--lr-purple-dark': colors.purpleDark,
} as CSSProperties
