import { NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

function makeSupabaseClient(cookieStore?: Awaited<ReturnType<typeof cookies>>) {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore?.getAll() ?? [], setAll: () => {} } }
  )
}

function makeTokenClient(token: string) {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { global: { headers: { Authorization: `Bearer ${token}` } } }
  )
}

async function getAuthContext(request: Request) {
  const authHeader = request.headers.get('Authorization')
  const bearerToken = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null
  if (bearerToken) {
    const { data: { user } } = await makeSupabaseClient().auth.getUser(bearerToken)
    return { user, db: makeTokenClient(bearerToken) }
  }
  const cookieStore = await cookies()
  const db = makeSupabaseClient(cookieStore)
  const { data: { user } } = await db.auth.getUser()
  return { user, db }
}

export async function GET(request: Request) {
  const { user, db } = await getAuthContext(request)

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Fetch all attempts by this user
  const { data: attempts, error: attemptsError } = await db
    .from('quiz_attempts')
    .select('id, quiz_id, score, completed_at')
    .eq('user_id', user.id)
    .order('completed_at', { ascending: true })

  if (attemptsError) {
    console.error('Stats attempts error:', attemptsError)
    return NextResponse.json({ error: 'Failed to fetch stats' }, { status: 500 })
  }

  // Fetch quizzes generated by this user
  const { data: generatedQuizzes } = await db
    .from('quizzes')
    .select('id')
    .eq('user_id', user.id)

  // Fetch topic info for quizzes the user has taken
  const takenQuizIds = [...new Set((attempts ?? []).map((a) => a.quiz_id))]
  let topicsExplored = 0
  if (takenQuizIds.length > 0) {
    const { data: takenQuizzes } = await db
      .from('quizzes')
      .select('topic')
      .in('id', takenQuizIds)
    const distinctTopics = new Set((takenQuizzes ?? []).map((q) => q.topic))
    topicsExplored = distinctTopics.size
  }

  const allAttempts = attempts ?? []
  const quizzesTaken = allAttempts.length
  const quizzesGenerated = (generatedQuizzes ?? []).length

  // Average score
  const avgScore =
    quizzesTaken > 0
      ? Math.round(allAttempts.reduce((sum, a) => sum + a.score, 0) / quizzesTaken)
      : null

  // Streak: consecutive days with at least one attempt, ending today or yesterday
  let streak = 0
  if (quizzesTaken > 0) {
    const today = new Date()
    today.setUTCHours(0, 0, 0, 0)
    const yesterday = new Date(today)
    yesterday.setUTCDate(yesterday.getUTCDate() - 1)

    // Build set of distinct days (UTC date strings) that had attempts
    const attemptDays = new Set(
      allAttempts.map((a) => {
        const d = new Date(a.completed_at)
        d.setUTCHours(0, 0, 0, 0)
        return d.getTime()
      })
    )

    // Find most recent attempt day that is today or yesterday
    const mostRecentDay = Math.max(...Array.from(attemptDays))
    const mostRecentDayMs = mostRecentDay

    if (mostRecentDayMs >= yesterday.getTime()) {
      // Count backwards from most recent day
      let current = mostRecentDayMs
      while (attemptDays.has(current)) {
        streak++
        current -= 86400000 // subtract one day in ms
      }
    }
  }

  // Avg improvement: average of (last_score - first_score) per quiz with multiple attempts
  let avgImprovement: number | null = null
  if (quizzesTaken > 0) {
    const attemptsByQuiz = new Map<string, { score: number; completed_at: string }[]>()
    for (const a of allAttempts) {
      const arr = attemptsByQuiz.get(a.quiz_id) ?? []
      arr.push({ score: a.score, completed_at: a.completed_at })
      attemptsByQuiz.set(a.quiz_id, arr)
    }

    const improvements: number[] = []
    for (const [, quizAttempts] of attemptsByQuiz) {
      if (quizAttempts.length >= 2) {
        // Already sorted ascending by completed_at from DB query
        const first = quizAttempts[0].score
        const last = quizAttempts[quizAttempts.length - 1].score
        improvements.push(last - first)
      }
    }

    if (improvements.length > 0) {
      avgImprovement = Math.round(improvements.reduce((s, v) => s + v, 0) / improvements.length)
    }
  }

  return NextResponse.json({
    quizzesTaken,
    topicsExplored,
    quizzesGenerated,
    avgScore,
    streak,
    avgImprovement,
  })
}
